name: release-please
on:
  push:
    branches:
      - main
    #paths:
    #  - 'src/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  release-please:
    # Only run for non-Dependabot PRs
    # if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
      # The logic below handles the npm publication:
      - name: Checkout Repository
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}

        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to npm
        # Release Please has already incremented versions and published tags, so we just
        # need to publish all unpublished versions to NPM here
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
